name: pipa_mov
description: "Pipa Móv - App de gestión de flotilla de pipas de agua."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
    # Cuando conectes el backend NestJS, agrega:
    # dio: ^5.7.0
  # ya no se ocupó Dio, se ocupó http: ^1.1.0
  http: ^1.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
